// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVW5ZUbOjP2NnOxCgJsL5dzIKMWhkUb54',
    appId: '1:249278663051:web:accf830dbd9498f4cd878e',
    messagingSenderId: '249278663051',
    projectId: 'mynotes-5f8b2',
    authDomain: 'mynotes-5f8b2.firebaseapp.com',
    storageBucket: 'mynotes-5f8b2.firebasestorage.app',
    measurementId: 'G-WS1DGJ5KW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11PtFE0ZMN8gr9ihJd1fLfT8yTe9j2_8',
    appId: '1:249278663051:android:62a5b38b7ba44375cd878e',
    messagingSenderId: '249278663051',
    projectId: 'mynotes-5f8b2',
    storageBucket: 'mynotes-5f8b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjqbR1fUODDnikWbrNSM52IPBoKcRfrM',
    appId: '1:249278663051:ios:098bb17ce051b34ecd878e',
    messagingSenderId: '249278663051',
    projectId: 'mynotes-5f8b2',
    storageBucket: 'mynotes-5f8b2.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjqbR1fUODDnikWbrNSM52IPBoKcRfrM',
    appId: '1:249278663051:ios:098bb17ce051b34ecd878e',
    messagingSenderId: '249278663051',
    projectId: 'mynotes-5f8b2',
    storageBucket: 'mynotes-5f8b2.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVW5ZUbOjP2NnOxCgJsL5dzIKMWhkUb54',
    appId: '1:249278663051:web:c4080bd025946a21cd878e',
    messagingSenderId: '249278663051',
    projectId: 'mynotes-5f8b2',
    authDomain: 'mynotes-5f8b2.firebaseapp.com',
    storageBucket: 'mynotes-5f8b2.firebasestorage.app',
    measurementId: 'G-L3FESZTBYK',
  );
}
